# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 16:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('des', models.CharField(max_length=25)),
                ('server_port', models.IntegerField(default=8000, verbose_name='\u542f\u52a8\u7aef\u53e3')),
                ('created', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('des', models.CharField(max_length=25)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('param', models.CharField(blank=True, max_length=255, null=True)),
                ('is_null', models.BooleanField(default=True, help_text='\u662f\u5426\u4e3a\u7a7a')),
                ('is_filter', models.BooleanField(default=False, help_text='\u5141\u8bb8\u7b5b\u9009')),
                ('is_search', models.BooleanField(default=False, help_text='\u5141\u8bb8\u641c\u7d22')),
                ('default_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u9ed8\u8ba4\u503c')),
                ('widget', models.CharField(max_length=255, verbose_name='\u90e8\u4ef6')),
                ('filters', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7b5b\u9009\u6761\u4ef6')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images', verbose_name='\u56fe\u7247')),
            ],
        ),
        migrations.CreateModel(
            name='SereverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.GenericIPAddressField(verbose_name='\u4e3b\u673a\u5730\u5740')),
                ('host_port', models.IntegerField(default=22, verbose_name='\u4e3b\u673a\u7aef\u53e3')),
                ('host_user', models.CharField(help_text='\u4e0d\u63a8\u8350\u4f7f\u7528root', max_length=50, verbose_name='\u7528\u6237\u540d')),
                ('host_password', models.CharField(max_length=255, verbose_name='\u7528\u6237\u5bc6\u7801')),
                ('project_path', models.CharField(default='~/projects', help_text='\u9ed8\u8ba4\u7528\u6237\u4e3b\u76ee\u5f55projects', max_length=255, verbose_name='\u5de5\u7a0b\u8def\u5f84')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_servers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('des', models.CharField(max_length=25)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='codeeditor.AppModel')),
            ],
        ),
        migrations.AddField(
            model_name='fieldmodel',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='codeeditor.TableModel'),
        ),
        migrations.AddField(
            model_name='appmodel',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_apps', to='codeeditor.SereverModel'),
        ),
        migrations.AddField(
            model_name='appmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_apps', to=settings.AUTH_USER_MODEL),
        ),
    ]
