# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 17:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeeditor', '0002_auto_20171215_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodel',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_apps', to='codeeditor.SereverModel'),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_apps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fieldmodel',
            name='des',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='fieldmodel',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='codeeditor.TableModel'),
        ),
        migrations.AlterField(
            model_name='tablemodel',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='codeeditor.AppModel'),
        ),
    ]
