# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeeditor', '0008_auto_20171221_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='serevermodel',
            name='host_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u4e3b\u673a\u540d\u79f0'),
        ),
    ]
