# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeeditor', '0010_auto_20180102_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodel',
            name='img_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
