# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeeditor', '0011_appmodel_img_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmodel',
            name='choices_value',
            field=models.TextField(blank=True, null=True, verbose_name='\u9009\u62e9\u5185\u5bb9'),
        ),
    ]
