# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeeditor', '0016_auto_20180207_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_set', models.CharField(help_text='\u65b0\u589eapp', max_length=255)),
                ('des', models.TextField(help_text='\u63cf\u8ff0')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_set', to='codeeditor.AppModel')),
            ],
        ),
        migrations.AlterField(
            model_name='historicalappmodel',
            name='history_type',
            field=models.CharField(choices=[('+', '\u5df2\u521b\u5efa'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalfieldmodel',
            name='history_type',
            field=models.CharField(choices=[('+', '\u5df2\u521b\u5efa'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalfilemodel',
            name='history_type',
            field=models.CharField(choices=[('+', '\u5df2\u521b\u5efa'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalserevermodel',
            name='history_type',
            field=models.CharField(choices=[('+', '\u5df2\u521b\u5efa'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicaltablemodel',
            name='history_type',
            field=models.CharField(choices=[('+', '\u5df2\u521b\u5efa'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
    ]
