# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeeditor', '0017_auto_20180308_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltablemodel',
            name='is_history',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4fdd\u5b58\u64cd\u4f5c\u8bb0\u5f55'),
        ),
        migrations.AddField(
            model_name='tablemodel',
            name='is_history',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4fdd\u5b58\u64cd\u4f5c\u8bb0\u5f55'),
        ),
        migrations.AlterField(
            model_name='fieldmodel',
            name='des',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='fieldmodel',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='fieldmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u540d\u5b57'),
        ),
        migrations.AlterField(
            model_name='fieldmodel',
            name='param',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u53c2\u6570'),
        ),
        migrations.AlterField(
            model_name='fieldmodel',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='codeeditor.TableModel', verbose_name='\u6240\u5c5e\u8868\u683c'),
        ),
        migrations.AlterField(
            model_name='historicalappmodel',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalfieldmodel',
            name='des',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='historicalfieldmodel',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='historicalfieldmodel',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalfieldmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u540d\u5b57'),
        ),
        migrations.AlterField(
            model_name='historicalfieldmodel',
            name='param',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u53c2\u6570'),
        ),
        migrations.AlterField(
            model_name='historicalfilemodel',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalserevermodel',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicaltablemodel',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
    ]
